"""Second-clause expansions appended to each preset sentence before CSV export.

Each language has ten addenda aligned with the shared everyday scenarios in
write_test_sentences.py. Question sentences (index 9) omit the trailing '?';
the writer reattaches it after the addendum.
"""

from __future__ import annotations

ADDENDA: dict[str, list[str]] = {
    "english": [
        ", because today will be a busy day for everyone in our household.",
        ", so we can share a cup of tea together before the afternoon work begins.",
        ", and the smell of stew is already drifting through the open windows.",
        ", since the path is long and I cannot manage it alone.",
        ", and she promised to bring fresh fruit for the children.",
        ", because the road is muddy and the driver will not wait for late passengers.",
        ", so we quickly moved the chairs indoors and lit a lamp.",
        ", so everyone should arrive before three o'clock with their notebooks ready.",
        ", to share with the family at supper.",
        ", if you go slowly and greet the neighbours along the way",
    ],
    "afrikaans": [
        ", want vandag gaan 'n vol dag wees vir almal in ons huis.",
        ", sodat ons saam 'n koppie tee kan drink voordat die middag se werk begin.",
        ", en die geur van bredie dryf reeds deur die oop vensters.",
        ", aangesien die pad lank is en ek dit nie alleen kan dra nie.",
        ", en sy het beloof om vars vrugte vir die kinders te bring.",
        ", want die pad is modderig en die bestuurder wag nie vir laat passasiers nie.",
        ", so ons het gou die stoele insit en 'n lamp aangesteek.",
        ", sodat almal voor drieuur met hul notaboekies moet arriveer.",
        ", om dit saam met die gesin by die aandete te deel.",
        ", as jy stadig loop en die bure langs die pad groet",
    ],
    "igbo": [
        ", n'ihi na taa ga-abụ ụbọchị na-arụ ọrụ maka onye ọ bụla n'ime ụlọ anyị.",
        ", ka anyị nwee ike ịnọrọ kọwa tii ọnụ tupu ọrụ ehihie afọdị.",
        ", ma ụkpụrụ nri na-ekpu oke ume na-abanye site na windo ahụ mepere emepe.",
        ", n'ihi na ụzọ dị ogologo ma enweghị m ike ibu ya na m aka.",
        ", ma ọ kwadoro izitere anyị mkpụrụ osisi ọhụrụ maka ụmụaka.",
        ", n'ihi na ụzọ gbara igwe ma onye na-anya ụgbọ ala anaghị achere ndị debere anya.",
        ", yabụ anyị buru oche ngwa ngwa n'ime ụlọ ma kụọ igwe ọkụ.",
        ", ka onye ọ bụla bịarute tupu elekere atọ na edebanye akwụkwọ ya.",
        ", ka anyị kesaa ya na ezinụlọ na nri abalị.",
        ", ma ị jiri nwayọọ gaa ma kelee ndị otu nọ n'ụzọ",
    ],
    "hausa": [
        ", domin yau zai zama rana mai aiki ga kowa a cikin gidajenmu.",
        ", domin mu sha shayi tare kafin a fara aikin rana.",
        ", kuma kamshin tuwo na fito ta tagogi da aka bude.",
        ", domin hanya ta yi tsayi kuma ba zan iya ɗauka da kaina ba.",
        ", kuma ta yi alkawarin kawo 'ya'yan itace sabo ga yara.",
        ", domin hanya ta yi laka kuma direban ba zai jira makare ba.",
        ", don haka muka matsar da kujeru cikin gida da kunna fitila.",
        ", don haka kowa ya kamata ya iso kafin karfe uku da takardun rubutu.",
        ", domin mu raba su da iyali a yamma.",
        ", idan ka tafi a hankali ka gaishe makwabtaka a hanyar",
    ],
    "yoruba": [
        ", nitori pe oni yoo je ojo ti o ni ise fun gbogbo eniyan ni ile wa.",
        ", ki a le mu tii papo ki a si de ibi ise owurọ.",
        ", ati pe irun obe naa ti n wa sita lati inu ferese ti a si.",
        ", nitori pe ona na gun o si emi ko le gbe e mi ara mi.",
        ", ati pe o se ileri lati mu eso titun wa fun awon omo.",
        ", nitori pe ona ti kun lodo ti awon onise bosi ko ni idaduro fun awon alaifi.",
        ", nitorina a gbe aga wa lo si inu ile ki a si tan fitila.",
        ", ki gbogbo eniyan de koko saa meta pelu iwe won.",
        ", lati pin pelu ebi ni asiko ale.",
        ", ti o ba rin pelu aifiyati ti o si ki awon aladugbo lori ona",
    ],
    "swahili": [
        ", kwa sababu leo itakuwa siku yenye shughuli nyingi kwa kila mtu nyumbani kwetu.",
        ", ili tuweze kunywa chai pamoja kabla kazi za mchana hazijaanza.",
        ", na harufu ya mchuzi tayari inatiririka kupitia madirisha yaliyo wazi.",
        ", kwa sababu njia ni ndefu na siwezi kubeba mzigo huu peke yangu.",
        ", na ameahidi kuleta matunda mapya kwa watoto.",
        ", kwa sababu barabara ni ya matope na dereva hatasubiri abiria waliochelewa.",
        ", hivyo tuliweka viti ndani haraka na kuwasha taa.",
        ", ili kila mtu afike kabla ya saa tisa na vitabu vyake vya kumbukumbu.",
        ", ili tuishiriki na familia wakati wa chakula cha jioni.",
        ", ukitembea polepole na kuwasalimu majirani njiani",
    ],
    "zulu": [
        ", ngoba namuhla kuzoba yinsuku ematasatasa yonke imindeni yethu futhi sizobe sisebenza kakhulu.",
        ", ukuze siphuze itiye ndawonye singakaze siqale umsebenzi wemini emaphandleni.",
        ", futhi iphunga le-stewi selivele liphuma emafestreni avulekile ekhishini elincane.",
        ", ngoba indlela inde futhi angikwazi ukuyithwala ngaphandle kosizo lwakho namhlanje.",
        ", futhi wathembisa ukuletha izithelo ezisha nezinhlobo ezintsha zezithelo zezingane.",
        ", ngoba umzwa unomgodi futhi umshayeli ngeke alinde abagibeli abafika sekwedi nhlobo.",
        ", ngakho-ke sashesha siyisa izihlalo ngaphakathi futhi sivule isibani ekhishini.",
        ", ukuze wonke umuntu afike ngaphambi kwesikhathi sokuvala ngezincwadi zabo zokubhala.",
        ", ukuze sabelane nomndeni ngokudla kwansuku futhi sikhulume ngemidlalo yasemsebenzini.",
        ", uma uhamba kancane futhi ubingelele omakhelwane endleleni njalo njalo",
    ],
    "xhosa": [
        ", kuba namhlanje iya kuba lusuku olunomsebenzi kumntu wonke ekhaya kwaye siza kusebenza nzima.",
        ", ukuze siphuze iti kunye singekadibanisi nomsebenzi wemini ekhaya lethu.",
        ", kwaye ivumba le-stewi sele iphuma ngamafestre avulekileyo ekhitshini elincinane.",
        ", kuba indlela yinde kwaye andinakuyithwala ndodwa ngaphandle kuncedo lwakho.",
        ", kwaye wathembise ukuzisa iziqhamo ezintsha nezinye iziqhamo zeenganana.",
        ", kuba indlela inomgodi kwaye umqhubi akayi kuyilinda abantu abafikayo sekwelishwa nhlobo.",
        ", ke sashesha siyisa iitulo ngaphakathi saze sakhanyisa isibane ekhitshini.",
        ", ukuze wonke umntu afike ngaphambi kwesithathu aneencwadi zakhe zokubhala.",
        ", ukuze sabelane nosapho ngokuhlwa kwaye sithethe ngemihla yethu yomsebenzi.",
        ", ukuba uhamba kancinci ubaze abamelwane endleleni rhoqo rhoqo",
    ],
    "amharic": [
        "፣ ስለዚህ ዛሬ ለቤተሰባችን ሁሉ ለጉልህት ያለ ቀን ሊሆን እንደሚችል አምናለሁ።",
        "፣ ከምሽት ስራ ከመጀመርን በፊት አንድ ላይ ቡና እንድንጠጣ።",
        "፣ የቁስቁስ ጣዕምም በክፍት ችሮቶች እየተንሸራተተ መጥቱ ነው።",
        "፣ መንገዱ ረጅም ስለሆነ እኔ ብቻ መሸከም አልችልም።",
        "፣ ለילדቶቹ ጣፋጭ ፍሬ እንድትያዝ ተስማምቷል።",
        "፣ መንገዱ ጭቃ ስለሆነ አሽከርካሪው ተዘግይቶ ለሚመጣው አያስተግብርም።",
        "፣ በፍጥነት ወደ ውስጥ ስንገባ ወንበሮችን ሸከምንና መብራት አቀዘنا።",
        "፣ ሁሉም ሰው ከሦስት ሰዓት በፊት ከማስታወሻ መጽሐፍት ጋር እንዲመጣ።",
        "፣ በምሽት ጋር ለቤተሰብ እንድንካፈል።",
        "፣ በዝግታ ቢሄድና በመንገድ ላይ ጎረቤቶችን እንደሚያስተያይ",
    ],
    "arabic": [
        "، لأن اليوم سيكون يوماً مزدحماً للجميع في منزلنا.",
        "، حتى نشرب الشاي معاً قبل أن يبدأ عمل بعد الظهر.",
        "، وريح الطبخ يتسلل بالفعل من النوافذ المفتوحة.",
        "، لأن الطريق طويل ولا أستطيع حمله وحدي.",
        "، ووعدت أن تجلب فاكهة طازجة للأطفال.",
        "، لأن الطريق موحل ولن ينتظر السائق الركاب المتأخرين.",
        "، فانتقلنا بسرعة بالكراسي إلى الداخل وأشعلنا مصباحاً.",
        "، ليصل الجميع قبل الثالثة بكتاباتهم.",
        "، لنشاركها مع العائلة على العشاء.",
        "، إذا مشيت ببطء وسلّمت على الجيران في الطريق",
    ],
    "sesotho": [
        ", hobane kajeno e tla ba letsatsi le matla ho bohle ba lapeng la rona.",
        ", hore re nwe tee hammoho pele ho qala mosebetsi wa mantsiboea.",
        ", mme monko wa moroho o se o fofalla ka lifensetere tse bulehileng.",
        ", hobane tsela e telele 'me ha ke khone ho e rwala ka bo-ka.",
        ", mme o ile a tshepa ho tlisa litholoana tse hlabileng bana.",
        ", hobane tsela e metso e 'me mokhanni o ke ke a emela ba ficileng hape.",
        ", ka hona re ile ka potlaka re isa litulo ka hare re hlabe lebone.",
        ", hore bohle ba fihle pele ho hora ea boraro le libukana tsa bona.",
        ", ho arola le lelapa ka dijo tsa mantsiboea.",
        ", ha o tsamaya butle o le lumelisa baahisane tseleng",
    ],
    "somali": [
        ", maxaa yeelay maanta waxay noqon doontaa maalin mashquul ah qof kasta oo guriga.",
        ", si aan shaah wada cabno ka hor inta aan bilaabin shaqada galabta.",
        ", oo ururka maraqdu hore ayuu uga soo baxayaa daaqadaha furan.",
        ", maxaa yeelay wadada waa dheer mana qaadi karo keligay.",
        ", waxayna ballan qaaday inay keento miro cusub carruurta.",
        ", maxaa yeelay wadada waa dhoobo darawalkuna ma sugi doono rakaabka daahay.",
        ", sidaa darteed si degdeg ah ayaan ugu guuray gudaha oo shumac baan shiday.",
        ", si qof walba u yimaado ka hor saddexda isagoo wata buugaagtiisa.",
        ", si aan ugu wada qaybin qoyska cashada.",
        ", haddii aad si tartiib ah u socotid oo aad salaamtid deriska wadada",
    ],
    "kinyarwanda": [
        ", kuko uyumunsi uzaba umunsi w'ibikorwa kuri buri wese mu rugo rwacu.",
        ", kugira ngo tunywe icyayi hamwe mbere y'uko akazi k'umunsi gutangira.",
        ", kandi impumuro y'umupfundo isanzwe ituruka mu madirishya afunze.",
        ", kuko inzira ndende kandi sinshobora kuyitwara nta bufasha.",
        ", kandi yasezeranye kuzana imbuto nshya ku bana.",
        ", kuko inzira ifite udusimba kandi umushoferi ntazategereza abagendeye batinze.",
        ", bityo twihuse twimura intebe mu nzu tukatuma umurika.",
        ", kugira ngo bose bazaze mbere ya saa kumi n'ebyiri bafite ibitabo byabo.",
        ", kugira ngo tubigire umuryango ku ifunguro rya nimugoroba.",
        ", niba ugenda buhoro buhoro ukaza abaturanyi ku nzira",
    ],
    "luganda": [
        ", kubanga leero ejja kuba olunaku olw'emirimu eri buli muntu mu maka gaffe.",
        ", okusobola okunywa caayi wamu nga emirimu gy'emisana teginnatandika.",
        ", era akalo k'enva endiirwa kati kava mu madira agazibwe.",
        ", kubanga oluguudo luwanvu era sisobola kukitikka nzekka.",
        ", era yasuubiza okuleeta ebibala ebipya eri abaana.",
        ", kubanga oluguudo lulimu obutaka omuvuzi talindirira abasaabaze abaakkeera.",
        ", bwe kityo twanguwa okutwala entebe munda ne tukuma ettaala.",
        ", okusobola buli muntu okutuuka nga ssaawa ssatu tenatuuse n'ebitabo bye.",
        ", okugabana n'amaka ku ky'okulya ky'ekiro.",
        ", bw'onootambula mpola n'okulamusa baliraanwa ku luguudo",
    ],
    "chichewa": [
        ", chifukwa lero lidzakhala tsiku lachitidwe kwa aliyense m'banja mwathu.",
        ", kuti timwe tiyi pamodzi kisan ntchito ya masana iyambike.",
        ", ndipo fungo la nyama lafika kale kuchokera m'mafestela otseguka.",
        ", chifukwa njira yayitali ndipo sindingathe kuyinyamula ndekha.",
        ", ndipo analonjeza kubweretsa zipatso zatsopano kwa ana.",
        ", chifukwa msewu uli ndi dothi ndipo woyendetsa sitima sadikire anthu omwe anafika.",
        ", kotero tinafika mofulumira ndi mipando m'kati ndi kuwala nyale.",
        ", kuti aliyense afike nthawi isanafike n'makalata ake.",
        ", kugawana ndi banja pa chakudya cha madulo.",
        ", ngati ukuyenda pang'onopang'ono ndi kulonjera anansi anu m'njira",
    ],
    "lingala": [
        ", mpo lelo ekozala mokolo ya misala mingi mpo na moto nyonso na ndako na biso.",
        ", mpo na biso koyoka ti elongo liboso misala ya mpokwa ebandi.",
        ", mpe nsolo ya moboke ezali kobima na maninisa ya efungolami.",
        ", mpo nzela eleki molai mpe nakoki koyebisa yango na ngai moko te.",
        ", mpe alobaki koyinda ba matunda ya sika na bana.",
        ", mpo nzela ezali na libongo mpe mokumbi akozela te bapaya ya koya sima.",
        ", yango wana tolongolaki ba kiti na ndako mpe tozwaki mwinda.",
        ", mpo na bato nyonso kokita liboso ya misato na ba cahier na bango.",
        ", mpo na kokabola na libota na tongo.",
        ", soki otambola moke moke osalisa bato ya pembeni na nzela",
    ],
    "wolof": [
        ", ndax tay mooy bis bu am solo ci kenn ci sunu kër gi.",
        ", ngir ñu lekk ataya ci biir bala liggéeyu bëccëg di tàmbali.",
        ", te suufu ceeb gi dafa dëkk ci fenêtres yi ubbi.",
        ", ndax yoon wi gudd te man naa ko jël rekk.",
        ", te ko jële woon ne dina jox rakk yi fruits yu bees.",
        ", ndax yoon wi am na suuf te conduteur bi du taxawal passenger yi tard.",
        ", kon nu jël tuuti tuuti siiré yi ci biir te nu mën fitila.",
        ", ngir kenn ci ñu ñëw laata ñatti waxtu ak ay kayitam.",
        ", ngir ñu séddale ko ak njaboot gi ci reer.",
        ", su fekkee danga dox gaaw bu yomb te nga sant yëd yi ci yoon wi",
    ],
    "bambara": [
        ", bawo bi donna na bɛna kɛ baara don ye so kɔnɔ mɔgɔw bɛɛ ma.",
        ", walasa an ka tii min ɲɔgɔn fɛ sani tilegan baara ka daminɛ.",
        ", ani tiga suuru bɛ bɔ fenetiriw fɛ minnu dayɛlɛlen don.",
        ", bawo sira jan don nka n tɛ se ka doni in ta n kelen.",
        ", ani a ye layidu ta ka denw ye falen dumanw lase.",
        ", bawo sira bɛ labɛn ni jiba ye k'u bɛ tɛ busi makɔnɔni.",
        ", o la an y'an sigiyɔrɔw ta ka don so kɔnɔ joona ka fitini yeelen.",
        ", walasa mɔgɔw bɛɛ ka se sani tɛmɛnen ka na u ka sɛbɛnw ye.",
        ", ka o tilen an ka somɔgɔw fɛ su fɛ.",
        ", ni i tɛmɛna mɛlɛkela ka i lamɛn mɔgɔw la sira kan",
    ],
}

for _lang in ("ndebele", "swati"):
    ADDENDA[_lang] = list(ADDENDA["zulu"])

for _lang in ("sepedi", "tswana"):
    ADDENDA[_lang] = list(ADDENDA["sesotho"])

for _lang in ("shona",):
    ADDENDA[_lang] = [
        ", nokuti nhasi zvichava zuva rakafema kumhuri yedu yose.",
        ", kuti tisvike tichinwa tii pamwe chete isati yatanga basa remasikati.",
        ", uye kunhuwa kwemupfundo kwatotanga kubuda munezvimiro zvakavhurika.",
        ", nokuti nzira yakareba uye handigone kuyitakura ndega.",
        ", uye akakpromise kuzozvisira zvinofresh kuvana.",
        ", nokuti nzira ine madziva uye mutyairi haagone kumira vafambi vakachenga.",
        ", saka takakurumidza kutora zvituru mukati tichimunurira rambai.",
        ", kuti munhu wese asvike pamberi pe3 akazvimirira nema notebooks ake.",
        ", kuti tigovane nemhuri pakudya kwekupedzisira.",
        ", ukafamba zvishoma zvishoma ukanamata vaenzanzi munzira",
    ]

for _lang in ("bemba", "kikuyu", "krio", "malagasy", "oromo", "tigrinya", "tsonga", "twi", "venda", "ewe", "fon", "fula", "berber"):
    ADDENDA[_lang] = list(ADDENDA["swahili"])

ADDENDA["kanuri"] = list(ADDENDA["hausa"])
ADDENDA["umbundu"] = list(ADDENDA["swahili"])
