"""Write ten everyday preset sentences for each evaluation language.

    python tools/write_test_sentences.py

Overwrites config/test_sentences.csv. English lines have no accent, so every
English accent offers the same ten sentences.
"""

from __future__ import annotations

import csv
import io
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUT = PROJECT_ROOT / "config" / "test_sentences.csv"

CODES = {
    "afrikaans": "AF",
    "amharic": "AM",
    "arabic": "AR",
    "bambara": "BM",
    "bemba": "BEM",
    "berber": "BER",
    "chichewa": "NY",
    "english": "EN",
    "ewe": "EE",
    "fon": "FON",
    "fula": "FF",
    "hausa": "HA",
    "igbo": "IG",
    "kanuri": "KR",
    "kikuyu": "KI",
    "kinyarwanda": "RW",
    "krio": "KRI",
    "lingala": "LN",
    "luganda": "LG",
    "malagasy": "MG",
    "ndebele": "ND",
    "oromo": "OM",
    "sepedi": "NSO",
    "sesotho": "ST",
    "shona": "SN",
    "somali": "SO",
    "swahili": "SW",
    "swati": "SS",
    "tigrinya": "TI",
    "tsonga": "TS",
    "tswana": "TN",
    "twi": "TW",
    "umbundu": "UMB",
    "venda": "VE",
    "wolof": "WO",
    "xhosa": "XH",
    "yoruba": "YO",
    "zulu": "ZU",
}

SENTENCES: dict[str, list[str]] = {
    "afrikaans": [
        "Goeie more, ek hoop jy het gisteraand rustig geslaap en lekker uitgerus tot die son opgekom het.",
        "Maak asseblief die deur agter jou toe en kom sit by ons om saam tee te drink.",
        "Die kinders speel sokker agter die huis terwyl hul ma nog besig is om middagete voor te berei.",
        "Kan jy asseblief help om hierdie swaar sak mielies vanmiddag hele pad na die mark toe te dra?",
        "My jonger suster kom môre vroeg op die eerste bus van die dorp af om ons te kom kuier.",
        "Ons moet vandag vroeg by die huis weg as ons die eerste bus na die dorp wil haal.",
        "Die reën het net begin stort toe ons klaar aandete gekook het en wou gaan sit om te eet.",
        "Sê asseblief vir jou pa dat die gemeenskapsvergadering van Donderdag na Vrydagmiddag verskuif is.",
        "Op pad huis toe van werk het ek vandag drie lemoene en 'n vars brood by die winkel gekoop.",
        "Hoe lank neem dit gewoonlik om te loop van die laerskool af tot by die rivier aan die rand van die dorp?",
    ],
    "amharic": [
        "እንደምን አደሩ፣ ትላንት ምሽት በደንብ እንደተኛህና ለጠዋቱ ለስላሳ እንደተነሳህ ተስፋ አደርጋለሁ።",
        "እባክህ በኋላህ ደጃውን ዝጋና ወደ ውስጥ መጥተህ ከእኛ ጋር ተቀመጥ እና ቡና እንጠጣ።",
        "ልጆቹ በቤቱ ጀርባ እግር ኳስ እየተጫወቱ ነው፣ እናታም እስከ ምሳ ያዘጋጁ ይገኛሉ።",
        "እባክህ ይህን ባጠበቀ የእህል ጥሬ ሻንጣ ዛሬ ከቀኑ በኋላ እስከ ገበያው እንድወስድትት ትረዳኛለህ?",
        "እህቴ ነገ ጠዋት በመጀመሪያው አውቶቡስ ከመንደር ስቀላ በጥዩ እንድትጎበኘን ተነስታለች።",
        "ዛሬ መጀመሪያውን አውቶቡስ ለመያዝ ከቤት በጥዩ መውጣት አለብን፣ አሁንም ጊዜው አልፎብናል።",
        "እራት ለመብላት ምግብ ለመስራት ከጨረስን ብቻ ዝናብ መጀመሩን ተመልክቷል፣ ሁሉም ወደ ውስጥ ሮጠ።",
        "ለአባትህ የማህበረሰቡ ስብሰባ ከሐሙስ ወደ ዓርብ ከሰዓት በኋላ እንደተዛወረ ተናግርለት።",
        "ዛሬ ከስራ በመመለስ በመንገድ ላይ ሦስት ብርቱካኖችና አንድ ገጠማ ገበዝያለሁ።",
        "ከመጀመሪያው ትምህርት ቤት እስከ ከተማውን የሚያጨልቀው ወንዝ ለመድረስ በእግር ምን ያህል ጊዜ ይወስዳል?",
    ],
    "arabic": [
        "صباح الخير، أتمنى أن تكون قد نمت جيداً الليلة الماضية واستيقظت وأنت تشعر بالراحة.",
        "من فضلك أغلق الباب خلفك وتعال اجلس معنا في الداخل لنشرب الشاي معاً.",
        "الأطفال يلعبون كرة القدم خلف البيت بينما أمهم ما زالت تعد الغداء في المطبخ.",
        "هل يمكنك مساعدتي في حمل هذه الحقيبة الثقيلة من الحبوب إلى السوق بعد ظهر اليوم؟",
        "أختي الصغرى ستأتي لزيارتنا من القرية صباح الغد في أول حافلة.",
        "علينا أن نغادر المنزل مبكراً اليوم إذا أردنا أن نلحق بأول حافلة إلى المدينة.",
        "بدأ المطر يهطل بقوة بعد أن انتهينا للتو من طبخ العشاء وكنا على وشك الجلوس.",
        "أخبر والدك من فضلك أن اجتماع المجتمع قد نُقل من يوم الخميس إلى يوم الجمعة بعد الظهر.",
        "في طريقي إلى المنزل من العمل توقفت اليوم واشتريت ثلاث برتقالات ورغيف خبز طازج.",
        "كم من الوقت يستغرق عادة المشي من المدرسة الابتدائية حتى النهر عند طرف البلدة؟",
    ],
    "bambara": [
        "I ni sogoma, n be nii ko i ye sunɔgɔ duman sɔrɔ su fɛ ka ban ka sɔgɔma kɛnɛya la.",
        "Aw ye da datugu aw kɔfɛ ka don an fɛ ka sigi an fɛ ka tii min ɲɔgɔn fɛ.",
        "Denmisɛnw bɛ bololankolon tan kɛ so kɔfɛ wa u ba bɛ tɔgɔla dumuni labɛn so kɔnɔ.",
        "I bɛ se ka n dɛmɛ ka nin sɛnɛfɛnw buru girin ta sugu la bi wula fɛ wa?",
        "N dɔgɔmuso bɛ na an lajɛ sini sɔgɔma ka bɔ dugu la tile fɔlɔ busi la.",
        "An ka kan ka bɔ so kɔnɔ joona bi sisan ni an b'a fɛ ka tile fɔlɔ busi ta.",
        "Sanji daminɛna o yɔrɔnin bɛɛ an ka dumuni tobi banlen kɔ ka sigi ka dumuni kɛ.",
        "I ka a fɔ i fa ye ko jama lajɛ in yɛlɛmana ka kɛ juma wula fɛ.",
        "N ye baara bɔ ka segin so, n ye lemuru saba ni mburu kura kelen san sira kan.",
        "A bɛ ta waati joli ka taa kalanso la ka se ba ma min bɛ dugu da la?",
    ],
    "bemba": [
        "Mwashibukeni, naletemwa ukuti mwabutuka bwino mu bushiku bwa jana na mwafika mu cine ca kucha.",
        "Mulembeni ulyo mulyango pa kumalilo kwenu na muleisa kumukala natwe mu ng'anda kuti tulelya icai pamodzi.",
        "Abana balecusha bantu pa kumalilo kwa ng'anda ilyo banyina balepekanya ifya kulya pa mafunde.",
        "Mulefwaya ukunwafwa ukutwala iyi nsakalilo ya nshima yalema ku maliketi mwalole lelo?",
        "Mukashi wandi wa kuchindikwa aleisa kutulemona kuchita ku mushi mailo mu cine ca kucha mu bese ya cine.",
        "Tulefwaya ukufuma pa ng'anda bwangu lelo nga tulefwaya ukukwata bese ya cine ukuya mu tauni.",
        "Imvula yalitampile ukuchita fye ilyo twapwile ukupanga ifya kulya na tulefwaya ukukala ukulya.",
        "Mwebe wishi ukuti umulongano wa mukaya wafushe ukufuma ku Lusosa ukuya ku Lwisano mu cine.",
        "Pa nshila yandi ukubwela ku ng'anda kuchita ku kucita, nalishita amacungwa yatatu na umukate wa kuchita.",
        "Cikwata inshita shinga ukuya ku sukulu ukufika ku mumana uuli pa mpela ya mushi?",
    ],
    "berber": [
        "Azul fell-awen, ttamɣan ad tettidired akken iwata iḍ uqbel u tettidired s lḥeqq.",
        "Ttxil-k meddel tawwurt deffir-ik u d-kem ad tqimeḍ akked-neɣ ad teswed atay.",
        "Igerdan tturaren uṭṭubal deffir n wexxam ma yella yemma-nsen tettwala tafat deg lexla.",
        "Tzemreḍ ad tɛawneḍ ad d-tawiɣ takaṭṭut-a tẓẓayen n uɣrum ɣer ssuq ass-a tadɣut?",
        "Tamtett-inu meẓẓiyen ad d-tas ad aɣ-terz ar sdat n taddart azekka s tbusa tamezwarut.",
        "Ilaɣ ad neffeɣ zik seg wexxam ma yella nebɣa ad neṭṭef tbusa tamezwarut i d-awḍen ɣer temdint.",
        "Tella tẓẓayen s tɣara deffir ma nkeḍ ad neɣleb tafat u nebɣa ad neqqim ad nečč.",
        "Ini-as i baba-k d akken timlilit n tɣerfa tettwafes seg uamass ɣer uḥeddu tadɣut.",
        "Srid ad d-uɣaleɣ seg uxeddim, ssiɣeɣ kraḍ n tlemmucin d aɣrum amaynut s ubrid.",
        "Acḥal n wakud i d-ittawi umeddu seg uɣerbaz agejdan ɣer wasif i d-yeglen deg ugur n temdint?",
    ],
    "chichewa": [
        "Mwadzuka bwanji, ndikuyembekeza kuti munagona bwino usiku watha ndi kuti mwadzuka molongoka m'mawa uno.",
        "Chonde tsekani chitseko m'mbuyo mwako ndipo lowani kuti mukakhale nafe kuti timumwe tiyi limodzi.",
        "Ana akusewera mpira kumbuyo kwa nyumba pomwe amayi awo akukonza chakudya m'khitchini.",
        "Kodi mungandithandize kunyamula thumba ili lathu la chimanga kupita ku msika madzulo ano?",
        "Mlonga wanga wamng'ono adzabwera kudzatichekera kuchokera ku mudzi m'mawa m'mawa pa basi yoyamba.",
        "Tiyenera kuchoka kwathu msanga lero ngati tikufuna kukwera basi yoyamba kupita ku tauni.",
        "Mvula yatanga kugwa kwambiri nthawi yomweyo timatopa kuphika chakudya ndipo tikanakhala pansi.",
        "Muuze bambo anu kuti msonkhano wa mdera wachotsedwa kuchokera ku Lachinayi kupita ku Lachisanu.",
        "Pa ulendo wanga wobwerera kunyumba kuchokera ku ntchito, ndinagula malalanje atatu ndi mkate watsopano.",
        "Zimatenga nthawi yayitali bwanji kuyenda kuchokera ku sukulu loyamba kupita ku mtsinje wa ku malo a mudzi?",
    ],
    "english": [
        "Good morning, I hope you had a restful night and slept well until the sun came up.",
        "Please close the door behind you and come inside to sit with us and have some tea.",
        "The children are playing football together behind the house while their mother finishes preparing lunch inside.",
        "Could you please help me carry this heavy bag of grain all the way to the market this afternoon?",
        "My younger sister is coming to visit us from the village early tomorrow morning on the first bus.",
        "We really need to leave home early today if we want to catch the first bus into town.",
        "The rain started pouring down just after we had finished cooking dinner and were about to sit down.",
        "Please tell your father that the community meeting has been moved from Thursday to Friday afternoon.",
        "On my way home from work today I stopped and bought three oranges and a fresh loaf of bread.",
        "How long does it usually take to walk from the primary school down to the river at the edge of town?",
    ],
    "ewe": [
        "Ŋdi nyuie, mele be nèdo dɔ dzi eye nèdo dɔ dzi le afi fifia eye nèdo kpɔ kpɔ.",
        "Taflatse tu ɖoɖo la megbe eye nàva nàkpe ɖe mía me be míakpɔ tii kple mía.",
        "Ðeviwo le fom le aƒe la megbe eye nɔnɔa le wɔ nuwo le kuxi me hafi woadi nu.",
        "Àte ŋu akpe mí be míakpɔ nuɖiɖi sia le ɖo le su la abe egbe?",
        "Nɔvi si me nye nɔnɔ si le vava tso du la egbe ɖeka le trotro gbãtɔ dzi.",
        "Ele be míadzo le afi la kaba egbe ne míele be míakpɔ trotro gbãtɔ la.",
        "Tsi dzi dzi egbe ɖeka hafi míawu nuwo wu eye míele be míakpɔ ɖo.",
        "Gblɔ na fofoa be nuƒoƒo la tsia tso yao dzi go yi fiɖa emegbe.",
        "Le míaƒe mɔ dzi tso dɔwɔwɔ la, mefle yibɔ etɔ̃ kple abolo yeyea le mɔ dzi.",
        "Ɣeyiɣi kae wòatsɔ aha tso suku susu la ayi tɔsisia si le du la dusime?",
    ],
    "fon": [
        "Kudeji, nɔ nyi ɖo alɔ bi ɖo hùn wɛ nyi do alɔ nyi nyɔn kpɔn kpɔn.",
        "Tu hɔntòn ɔ ɖo e gudo kpo e wa jijɛ kpo mí ɖo xo la mɛ tii.",
        "Vǐ lɛ ɖo bolu le xwe ɔ gudo hùn nɔ ɖo nu le kuxi la mɛ.",
        "A ɖo se ɖe nɔ wɛ ɖo nuɖiɖi lɛ lɛn ɖo su la mɛ lɛn?",
        "Nɔsi mɛ lɛn na wa yi du ji lɛn sɔ́n lɛn na wa lɛn.",
        "Mí nɔ yí xo la kaka egbe nɔ mí nɔ kpɔn trotro gbãtɔ la.",
        "Ji dó dó hùn mí wá nu lɛn kpo mí nɔ yí jijɛ kpo.",
        "Ɖɔ nú tɔ́ towe ɖɔ kplé ɔ yí juma emegbe ɖo axɔsuza la.",
        "Un xɔ̀ oranges atɔn kpo bléɖo yeyea le mɔ dzi sín nɔ wa gbé.",
        "Hwenu tɛ́ wɛ è na zán bo sín wemaxɔmɛ susu la yì tɔ́ ɔ gbé?",
    ],
    "fula": [
        "Jam waali, miɗa yiɗa a heɓa suudu ɗum ndiɗam e jaɓɓi e a firti e yontere.",
        "Tiiɗno uddu damal ngal caggal maa e a ar e a jooɗo e amen ngam mina tee.",
        "Sukaaɓe ɓee ngoniina ciya e fiyde caggal suudu haa ɗum nde baabooɓe mum ina waɗata nyaamdu.",
        "Aɗa waawi wallit-mi ndiyam ndee leɗɗal e gerte ɗoo fof e haa luumo hannde wulde?",
        "Doggotoore am yimɓe ngarta e haa suudu amen gobe subaka e lebus faaɗo faaɗo.",
        "Ee maaɗa e haa suudu jooni hannde so aɗa yiɗi heɓde lebus faaɗo ngam yahde e dugguure.",
        "Roobii fuɗii heen nde min timminii waɗde nyaamdu e min ngoni e noppi ngam jooɗde.",
        "Haalnu baaba maa wonde batu nguu uddii e Alkamar haa Aljumaa e ngoorɗe.",
        "E haa miɗo yahde e suudu e haa gollal, mi soodi leemuneeje tati e mburu hesɗo.",
        "Hoɗee foti yahde e leydi gila duɗal faaɗo faaɗo haa maayo ngam haa gede suudu?",
    ],
    "hausa": [
        "Barka da safiya, ina fatan ka yi barci lafiya a daren jiya kuma ka tashi da kyau.",
        "Don Allah rufe kofar bayanka ka shigo ka zauna tare da mu mu sha shayi tare.",
        "Yara suna wasa da kwallon kafa a bayan gida yayin da mahaifiyarsu ke karamar abincin rana a cikin kitchen.",
        "Za ka iya taimaka mini in ɗaga wannan jaka mai nauyi na hatsi zuwa kasuwa wannan rana?",
        "Ƙanwata ta fi ƙarami za ta zo daga ƙauyen gobe da safe a farkon mota.",
        "Dole ne mu fita daga gida da wuri yau idan muna son kama farkon mota zuwa birni.",
        "Ruwan sama ya fara zubar da wuri bayan mun gama dafa abincin dare kuma muna shirin zauna.",
        "Ka gaya wa mahaifinka cewa taron al'umma an canza shi daga Alhamis zuwa Juma'a da rana.",
        "A hanyata ta gida daga aiki na tsaya na sayi lemo uku da gurasa daya sabo.",
        "Nawa ne zai dauka yawo daga makarantar firamare zuwa kogi da ke gefen birni?",
    ],
    "igbo": [
        "Ụtụtụ ọma, achọrọ m ka ị mara na anụrụ m na ị zuru ụra ọma n'abalị gara aga.",
        "Biko mechie ụzọ azụ gị bịa nọrọ nọọ na anyị ka anyị nọrọ kọwa tii ọnụ.",
        "Ụmụaka na-egwu egwuregwu bọọlụ n'azụ ụlọ mgbe nne ha ka na-akwado nri ehihie n'ime ịkụ.",
        "Biko, ị ga-enyere m aka ibu akpa ọka a arọ na-akpọ ike gaa ahịa taa ehihie?",
        "Nwanne nwanyị m nke nta na-abịa gaa anyị n'oge ọma echi ututu site na obodo na ụgbọ ala mbụ.",
        "Anyị ga-achọ ịpụ n'ụlọ n'oge na-abịghị echi ma ọ bụrụ na anyị chọrọ ịnweta ụgbọ ala mbụ na obodo.",
        "Mmịrị mmịrị bidoro igba ozuzo mgbe anyị mechara ise nri abalị ma na-achọ ikpọrọ nọdụ.",
        "Gwa nna gị na nzukọ obodo ahụ gbanwere site na Tọzdee gaa na Fraịde n'ehihie.",
        "Na ụzọ m na-alaghachi ụlọ site na ọrụ, azụtara m oroma atọ na otu achịcha ọhụrụ.",
        "Olee ogologo oge ọ na-ewe ije site n'ụlọ akwụkwọ nke atọ ruo na osimiri nke dị na ngwụcha obodo?",
    ],
    "kanuri": [
        "Kachallowa, nǝm fǝle ngǝwu kǝla suudu ro fǝle kǝla kuru ndǝ kuru fǝle kǝla suudu ro ndǝ fǝle.",
        "Kǝla fǝre awo, ka don kǝla fato gǝre ka sigi gǝre, sannan nǝm shayi yeyi tare da mu.",
        "Feroanza kwallo kǝla fato gǝre kǝla suudu gǝre kǝlǝ amma ndǝ ci detǝ kǝla kuxi gǝre.",
        "Wu kasuwa ro lejin gowo bi wula kǝla buru girin kǝla fato gǝre kǝla kasuwa ro lejin?",
        "Kǝrǝmi am lejin kachallo kǝla dugu kǝla bas faaɗo lejin kǝla tauni gobe da safe.",
        "Kǝla fato joona lehono kǝla bas faaɗo kǝla tauni kǝla fǝle kǝla fato gǝre lejin.",
        "Dǝlǝgǝ daminǝna kǝla ci banlen kǝro kǝla fato gǝre, sannan ndǝ ci detǝ kǝla suudu gǝre.",
        "Aba nǝm ye taro yɛlɛmana kǝla Alhamis kǝla Juma wula fɛ, kǝla fato gǝre ka kawo.",
        "Wu lemu yaskǝ kǝla gurasa tilo so kǝla sira kan kǝla fato gǝre kuru ba'a ro lejin.",
        "Madrasa kǝla nji fǝle sawal kǝla dugu da kǝla kogi gǝre kǝla fato fǝle lejin?",
    ],
    "kikuyu": [
        "Ruciini ruega, nĩ ngũgwĩthĩrĩria nĩwarĩ mwega ũtukũ wa ira na ũkiumĩra ũmũthĩ.",
        "Ndakũhoya ũhinge mũrango wa thutha waku na ũingĩre ũikarane na ithuĩ twanyue cai hamwe.",
        "Ciana nĩciathakana mpira thuutha wa nyũmba rĩrĩa maitũ nĩmarekaga kũrĩga irio cia mũthenya.",
        "No ũndĩteithie kũkuua iratathi rĩa mũhũrũ rĩa mũhere harĩa ndũnyũ rĩu mũthenya wa rũcinĩ?",
        "Mwarĩ wa nyina wakwa mũnini nĩũũka gũtũcererera kuma kũu rũciaro rũcinĩ wa rũciũ na basi ya mbere.",
        "Tũrabatara kuuma mũciĩ iria rĩu rĩu tũrĩ kwĩra basi ya mbere ĩgũthiĩ tauni-inĩ.",
        "Mbura nĩyambĩrĩirie kũnyũma o rĩrĩa twathira kũrĩga irio cia rũcinĩ na twĩ mbaru gũikara.",
        "Ĩra ithe waku atĩ mũcemanio wa gũkũ wa mũciĩ nĩwagũrũtwo kuuma Alhamisi akĩthiĩ Ijumaa mũthenya wa rũcinĩ.",
        "Thĩiniĩ wa njĩra yakwa ya gũcoka mũciĩ kuuma wĩra, nĩndagũrire macungwa matatũ na mũgate mwega.",
        "Nĩ ihinda rĩigana rĩkũoya gũthiĩ na magũũ kuuma sukuru ya mbere nginya rũũi-inĩ rũrĩa rũ thĩiniĩ wa tauni?",
    ],
    "kinyarwanda": [
        "Mwaramutse, nizere ko mwaryamye neza ijoro rishize kandi mwabyutse neza uyu munsi mu gitondo.",
        "Nyamuneka funga urugi inyuma yawe hanyuma winjire uce ukicara natwe kugira ngo twanywe icyayi hamwe.",
        "Abana barakina umupira inyuma y'inzu mu gihe nyina wabo ari gukurura ifunguro rya saa sita mu gikoni.",
        "Waba wanshoboye kumfasha gutwara iyi sakoshi iremereye y'ibigori kugeza ku isoko uyu munsi nyuma ya saa sita?",
        "Mushiki wanjye muto azaza kudusura avuye ku cyaro ejo mu gitondo cya kare ku bisi ya mbere.",
        "Tugomba gusohoka mu ngo vuba uyu munsi niba dushaka gukora bisi ya mbere ijya mu mujyi.",
        "Imvura yatangiye gukuba cyane nyuma y'uko twarangije guteka ifunguro rya nimugoroba kandi twari tugiye kwicara.",
        "Bwira so wawe ko inama y'umuryango yimuriwe uva ku wa Kane kugeza ku wa Gatanu nyuma ya saa sita.",
        "Mu nzira yanjye yo kujya mu ngo avuye ku kazi, nagize ngo nguze amacunga atatu n'umugati umwe mushya.",
        "Bimara igihe kingana iki kugenda n'amaguru uva ku ishuri ry'incuke ukajya ku ruzi ruri ku mpera y'umujyi?",
    ],
    "krio": [
        "Gud mɔnin, a hop se yu slip gud las nait en yu get op fayn dis mɔnin.",
        "Duya, shɛt di do bihain yu en kam insay siddɔn wit wi fo drink ti tɛgɛda.",
        "Di pikin dɛn de ply futbɔl bihain di os wɛn dɛn mama de kuk lunch insay di kichin.",
        "Yu fit ɛp mi kɛr dis big sak ɔf grin go makɛt dis aftanun?",
        "Mi sista we smɔl go kam visit wi frɔm di vilij tumara mɔnin in di fos bɔs.",
        "Wi fɔ liv di os iri tide if wi wan kɛt di fos bɔs we de go taun.",
        "Di ren stat fɔ pɔr dɔn jɔs afta wi don kuk dina en wi bin redi fo siddɔn.",
        "Tɛl yu papa se di mitin dɔn shif frɔm Torsde go Fraide aftanun.",
        "Pan mi we go os frɔm wok tide, a stop en bai tri ɔrinj ɛn wan fɛsh brod.",
        "Aw lɔng i go tek fɔ waka frɔm di praimeri skul dɔn go di riva we de na di ɛd ɔf taun?",
    ],
    "lingala": [
        "Mbote na ntongo, nalingi ete olobi malamu na butu eleki mpe omoni malamu lelo na ntongo.",
        "Svp kanga ekuke na nsima na yo mpe ya kati kofanda na biso mpo tokomela ti elongo.",
        "Bana bazali kosakana na football na sima ya ndako tango mama na bango azali kolamba bilei ya midi na kizini.",
        "Okoki kosalisa ngai kotambola na sac oyo ya makolo ya moke tii na zando lelo na mpokwa?",
        "Mokolo na ngai ya mwasi ya moke akoya kotala biso kowuta na mboka na ntongo ya lobi na bus ya liboso.",
        "Esengeli biso kobima na ndako yango na ntango lelo soki tolingi kokanga bus ya liboso oyo ekende na engumba.",
        "Mbula ebandi kobeta makasi nsima moke tosilaki kolamba bilei ya pokwa mpe tozali kobongisa kokita.",
        "Yebisa tata na yo ete likita ya mboka ebongisami kowuta na mardi kino vendredi na mpokwa.",
        "Na nzela na ngai ya kozonga na ndako kowuta na mosala, nasombi orange misato mpe lipa moko ya sika.",
        "Ezwaka ntango boni mpo na kotambola kowuta na eteyelo ya liboso kino ebale ya ezali na nsuka ya engumba?",
    ],
    "luganda": [
        "Wasuze otya, nsuubira nti wasula bulungi ekiro ekyayise era okolokose bulungi enkya ya leero.",
        "Nsaba oggale oluggi emabega wo oyingire otuule naffe munda tufune caayi wamu.",
        "Abaana bazannya omupiira emabega w'ennyumba nga nnyina baabwe akyakola ebyokulya by'emisana mu ffumbiro.",
        "Oyinza okuyamba okutikka ensawo eno enzito ey'emmere okugitwala ku katale leero emisana?",
        "Mwannyina wange omukyala omuto agenda kujja okutulaba ng'avudde ku kyalo enkya ya kesho ku bbaasi esooka.",
        "Tulina okuva awaka mangu leero bwe tuyagala okukwata bbaasi esooka egenda mu kibuga.",
        "Enkuba yatandise okutonnya nnyo nga tumaze okufumba eky'okulya ky'ekiro era nga twali tutegekera okutuula.",
        "Gamba kitaawo nti olukungaana lw'ekitundu luwedde okuva ku Lwokuna okudda ku Lwokutaano emisana.",
        "Ku luguudo lwange okudda awaka okuva ku mulimu, nagula emicungwa esatu n'omugaati omupya.",
        "Kitwala bbanga ki okutambula okuva ku ssomero ery'obwana okutuuka ku mugga oguli ku nkomerero y'ekibuga?",
    ],
    "malagasy": [
        "Manao ahoana ny maraina, manantena aho fa nandroso tsara ianao alina ary nifoha tsara androany maraina.",
        "Azafady hidio ny varavarana ao aorianao ary miditra mba hipetraka miaraka aminay hisotro dite.",
        "Milalao baolina kely ny ankizy ao ambadiky ny trano raha mbola manomana ny sakafo atoandro ny reniny ao an-dakozia.",
        "Afaka manampy ahy hitondra ity kitapo mavesatra ity amin'ny vary ho any an-tsena androany hariva ve ianao?",
        "Hisy ny rahavavy kely anay hiaviavy avy any ambanivohitra rahampitso maraina amin'ny fiara fitateram-bahoaka voalohany.",
        "Mila miala aloha isika androany raha te hihazo ny fiara fitateram-bahoaka voalohany mankany an-tanàna isika.",
        "Nanomboka nivatravatra ny orana taorian'ny nahavitanay nandraosana ny sakafo hariva ary efa nomaninay hipetraka.",
        "Lazao amin'ny rainy fa ny fivoriana fiaraha-monina dia nafindra avy ny Alakamisy ho amin'ny Zoma hariva.",
        "Tamin'ny lalana niverinako tany an-trano avy any amin'ny asa, nividy voasary telo sy mofo vaovao aho.",
        "Hatraiza ny fotoana fandehanana an-tongotra avy any amin'ny sekoly fototra mankany amin'ny ony eo am-paran'ny tanàna?",
    ],
    "ndebele": [
        "Livuke njani, ngiyethemba ukuthi ulale kahle ebusuku obudlule futhi uvuke kahle namhlanje ekuseni.",
        "Ngicela uvale umnyango ngemuva kwakho bese ungena uhlale nathi singaphuze itiye ndawonye.",
        "Abantwana badlala ibhola emuva kwendlu ngenkathi umama wabo esaphakela isidlo sasemini ekhishini.",
        "Ungangisiza ngithwale lesi sakhi esisindayo sokudla siye emakethe namhlanje ntambama?",
        "Udade wami omncane uzoza kusivakashela evela emaphandleni kusasa ekuseni ngebhasi yokuqala.",
        "Kufanele siphume ekhaya ngokushesha namhlanje uma sifuna ukubamba ibhasi yokuqala eya edolobheni.",
        "Imvula yaqala ukuna kakhulu ngemva kokuba sibe sesiqedile ukupheka isidlo sakusihlwa sizolala phansi.",
        "Tshela uyihlo ukuthi umhlangano womphakathi ususwe kusukela ngoLwesine uye ngoLwesihlanu ntambama.",
        "Endleleni yami yokubuyela ekhaya emsebenzini, ngiyethe ngathenga amawolintshi amathathu nesinkwa esisha.",
        "Kuthatha isikhathi esingakanani ukuhamba uvela esikolo sokuqala uye emfuleni okusekupheleni kwedolobha?",
    ],
    "oromo": [
        "Akkam bulte, abdii nan qaba inni kaleessa galgala gaarii rafitee har'a ganama gaarii kaate jirta.",
        "Maaloo balbala duuba kee cufiitii keessa seeni nu waliin taa'iitii shaayii waliin dhuguu.",
        "Daa'imman mana duuba kubbaa miilaa taphachaa jiru yeroo haati isaanii mana keessatti qophii nyaataa hojjettu.",
        "Boqonna kana ulfaataa midhaanii gara gabaa geessuuf har'a waaree booda na gargaaruu dandeessa?",
        "Obboleetti koo xiqqoon ganda irraa bor ganama buusii jalqabaa irratti nu argachuuf dhufa.",
        "Har'a mana irraa ariifachuun ba'uu qabna yoo buusii jalqabaa magaalatti qabachuu barbaanne.",
        "Roobni jalqabee dhangala'uu nyaata galgalaa xumnuu booda taa'uuf qophaa'uun dura.",
        "Abbaa keetiif walgahinni hawaasaa Kamiisaa irraa Jimaata waaree boodatti jijjiirame jedhi.",
        "Karaa gara manaa irraa hojii irraa deebi'uun har'a lamuu sadii fi daabboo haaraa tokko bitadhe.",
        "Mana barumsaa jalqabaa irraa gara lagaatti deemuf yeroo hammami fudhata, lagaan sun xiyyaara magaalaa jira?",
    ],
    "sepedi": [
        "Thobela, ke tshepa gore o robile gabotse bosiu bjo bo fetilegolo gomme o diphologile gabotse mesong ye.",
        "Hle tswalela lemati ka morago ga gago gomme o tsene o dule le rena ka gare gomme re nwe tee.",
        "Bana ba bapala bolo ka morago ga ntlo ge mma wa bona a sa ntse a lokisa dijo tsa masegare ka kitchineng.",
        "O ka ka nthuša go rwala monwana wo o boima wa dijo go ya mmarakeng mafelelo a lehono?",
        "Kgaitsadi ya ka yo monnyane o tla re etela a tswa motseng mesong ye ka bese ya pele.",
        "Re swanetše go tšwa ka gae ka pela lehono ge re nyaka go tšea bese ya pele e ya toropong.",
        "Pula e thomile go na ka maatla ka morago ga ge re feditše go pheka dijo tsa mafelo a lehono.",
        "Botša tatago gore kopano ya setšhaba e fetogile go tšwa Labone go ya Labohlano mafelelo a lehono.",
        "Tseleng ya ka ya go boela gae go tšwa mošomong, ke rekišitše maswiri a mararo le borotho bo bofsa.",
        "Go tšea nako e kae go sepela go tloga sekolong sa mathomo go ya nokeng e lego mafelelong a toropo?",
    ],
    "sesotho": [
        "Dumela, ke tshepile hore u robile hantle bosiu bo fetileng mme u fihlile hantle kajeno hoseng.",
        "Ka kopo kwala lemati ka morao ho wena o kene o dule le rona ka hare re nwe tee hammoho.",
        "Bana ba bapala bolo ka mora ntlo ha mme wa bona a ntse a lokisa lijo tsa motshehare ka kitchineng.",
        "Na u ka nthusa ho rwala mokotla ona o boima oa lijo ho ea mmarakeng mantsiboea kajeno?",
        "Usoana wa ka o monyane o tla re etela a tsoa motseng hosane ka bese ea pele.",
        "Re hloka ho tsoa lapeng kapele kajeno haeba re batla ho tšoara bese ea pele e ea toropong.",
        "Pula e qala ho na ka matla ka mora hore re qetile ho pheha lijo tsa mantsiboea mme re ne re loketse ho dula.",
        "Bolella ntatao hore kopano ea sechaba e fetisitsoe ho tloha Labone ho ea Labohlano mantsiboea.",
        "Tseleng ea ka ea ho khutlela lapeng ho tsoa mosebetsing, ke rekile namune tse tharo le bohobe bo bocha.",
        "Ho nka nako e kae ho tsamaya ho tloha sekolong sa mantlha ho ea nokeng e leng qetellong ea toropo?",
    ],
    "shona": [
        "Mangwanani, ndinovimba kuti wakoroga zvakanaka usiku hwapfuura uye wakakwidza zvakanaka nhasi mangwanani.",
        "Ndapota vharai musuwo kumashure kwenyu uye pindai mugara nesu tisvike tichinwa tii pamwe chete.",
        "Vana vari kutamba bhora kuseri kweimba vachiri kuti amai vavo vari kugadzirira chikafu chemasikati mukicheni.",
        "Unogona kundibatsira kutakura bag iri remazhinji rinosimba kuenda kumusika manheru ano?",
        "Hanzvadzi yangu mudiki achauya kutisuwa achibva kumusha mangwana mangwanani nebhazi rekutanga.",
        "Tinofanira kubuda kumba nekukurumidza nhasi kana tikuda kubata bhazi rekutanga rinobva kuchikoro.",
        "Mvura yakatanga kunaya zvakanyanya mushure mekuti tapedza kupika chikafu chemanheru tichigadzirira kugara pasi.",
        "Udza baba vako kuti musangano wevanhu wachinjwa kubva pachishanu kuenda pachishanu manheru.",
        "Penzira yangu yekudzoka kumba kubva kubasa, ndakatenga maorenji matatu nechingwa chitsva.",
        "Zvinotora nguva yakareba sei kufamba kubva kuchikoro chepasi kuenda kurwizi uri papemberi pemuguta?",
    ],
    "somali": [
        "Subax wanaagsan, waxaan rajeynayaa inaad si fiican u seexatay habeenkii hore oo aad si fiican u kacday maanta.",
        "Fadlan albaabka gadaashaada xir oo soo gal gudaha si aad ula fadhiisato annaga oo shaah wada cabno.",
        "Carruurtu waxay ku ciyaarayaan kubada guriga gadaashiisa halka hooyadood ay weli diyaarinayso qadada jikada.",
        "Ma i caawin kartaa inaan xamuulka culus ee hadhuudhka ah u qaado suuqa galabta maanta?",
        "Walaashay yar waxay nagu soo booqan doontaa tuulada berri subaxnimo baska ugu horreeya.",
        "Waa inaan guriga ka baxnaa goor hore maanta haddii aan rabno inaan qabano baska ugu horreeya ee magaalada.",
        "Roobku wuxuu bilaabay inuu si xoog leh u da'o isla markii aan dhamaynay karinta cashada oo aan diyaar u ahayn fadhi.",
        "Aabbahaa u sheeg in shirka bulshada laga wareejiyay Khamiis ilaa Jimcaha galabnimo.",
        "Jidkayga guriga ee shaqada ka imaanaya, waxaan soo iibsaday saddex liin iyo roodhi cusub.",
        "Intee in le'eg ayay qaadataa in laga lugeeyo dugsiga hoose ilaa webiga ku yaal geeska magaalada?",
    ],
    "swahili": [
        "Habari za asubuhi, natumai ulilala vizuri usiku wa jana na umeamka salama leo asubuhi.",
        "Tafadhali funga mlango nyuma yako na uingie ndani uketi nasi tupate kunywa chai pamoja.",
        "Watoto wanacheza mpira nyuma ya nyumba huku mama yao bado akiandaa chakula cha mchana jikoni.",
        "Unaweza kunisaidia kubeba mfuko huu mzito wa nafaka hadi sokoni mchana huu?",
        "Dada yangu mdogo atakuja kututembelea kutoka kijijini kesho asubuhi na basi la kwanza.",
        "Tunahitaji kuondoka nyumbani mapema leo ikiwa tunataka kushika basi la kwanza linalokwenda mjini.",
        "Mvua ilianza kunyesha sana mara tu tulipomaliza kupika chakula cha jioni na tulikuwa tunakaribia kukaa.",
        "Mwambie baba yako kuwa mkutano wa jamii umehamishwa kutoka Alhamisi hadi Ijumaa mchana.",
        "Njiani kurudi nyumbani kutoka kazini, nilisimama nikanunua machungwa matatu na mkate mpya.",
        "Inachukua muda gani kwa kawaida kutembea kutoka shule ya msingi hadi mto uliopo mwisho wa mji?",
    ],
    "swati": [
        "Sawubona ekuseni, ngiyetsemba kutsi ulale kahle ebusuku lobe lendlulile futsi uvuke kahle namuhla ekuseni.",
        "Ngiyacela uvale umnyango ngemuva kwakho bese ungena uhlale natsi siphuze litiye ndzawonye.",
        "Bantfwana badlala ibhola ngemva kwendlu ngenkathi boma babo basati apheka tifisiphi letikolwa ekhishini.",
        "Ungangisita ngikhetse lesi sakhi lesisindzile setidla siye emakethe namuhla emini?",
        "Udadewethu lomncane utawufika kusivakashela avela emaphandleni khusasa ekuseni ngebhasi lekucala.",
        "Sidzinga kudzinga ekhaya ngokushesha namuhla uma sifuna kubamba libhasi lekucala leya edolobheni.",
        "Imvula yacala kunaya kakhulu ngemuva kwekutsi sicedze kupheka tifisiphi letikolwa sibe silungele kuhlala phansi.",
        "Tjela uyihlo kutsi umhlangano wemiphakatsi ususwe kusuka ngeLwesine uye ngeLwesihlanu emini.",
        "Endleleni yami yekubuyela ekhaya kusuka emsebenzini, ngitsenge emawolintshi lamatsatfu nesinkhwa lesisha.",
        "Kutsatsa sikhatsi lesingakanani kuhamba kusuka esikolweni lesincane kuya emfuleni losedolobheni?",
    ],
    "tigrinya": [
        "ከመይ ሓዲርካ፣ ትማሊ ምሸት ጽቡቕ ገይርካ ከም ዝደቀስካ ተስፋ ይገብር።",
        "በጃኻ ኣብ ድሕሪኻ ኣድምቕ እሞ ኣብ ውሽጢ መጻእካ ምስና ኮፍ ኢኻ ቡን ክንሰተይ።",
        "ቆልዑ ኣብ ድሕሪ ገዛ እግር ኳስ ይጻወቱ ኣለዉ፣ ኣዶም ኣብ ኩሽና ምሳ ክሰርሑ ኣለዉ።",
        "በጃኻ እዚ ከቢድ ጥራዝ ዓረብ ክሳብ ዕዳጋ ክወስዶ እንተ ተረዲኡኒ?",
        "እሓትነይ ኣብ ጥዑም ጽባሕ ካብቲ መጀመርታ ባስ ካብ ዓዲ ክትመጽእ እያ።",
        "ሎሚ ነቲ መጀመርታ ባስ ክንወስዶ እንተ ደሊና ካብ ገዛ ቀዳም ክንወጽእ ኣለና።",
        "ዝናብ ብሓደሽነት ክሰርሕ ኣብ ጀሚሩ ንምሳ ክንበል ክንዳለና ንሰርሕ ኣብ ዝውድእሉ ግዜ።",
        "ንኣቦኻ ነቲ ናይ ማሕበረሰብ ኣኼባ ካብ ሓሙስ ናብ ዓርቢ ድሕሪ ቀትሪ እንተ ተዛወረ ገልጸሉ።",
        "ኣብ መንገዲ ካብ ስራሕ ናብ ገዛ፡ ሰለስተ ብርቱካንን ሓደ ሓድሽ ባኒን ገዚአ።",
        "ካብ ቀዳማይ ቤት ትምህርቲ ክሳብቲ ኣብ ጥቓሚ ከተማ ዘሎ ሩባዕ ንኸይድ ብእግሪ ክንደይ ግዜ ይወስድ?",
    ],
    "tsonga": [
        "Avuxeni, ndzi tshemba leswaku u etlele kahle vusiku byo hetileswa u ri na nkhensa namuntlha.",
        "Ndza kombela u pfala tinyangwa endzhaku ka wena u nghena u tshama na hina hi mina ti.",
        "Vana va tlanga bolo endzhaku ka yindlu laha mmanana wa vona a nga ri karhi a lungiselela swakudya swa maseko eka kitchini.",
        "Xana u nga ndzi pfuna ku tlakusa xikhwama lexi xisindzaka xa swakudya ku ya emakethe namuntlha madzahala?",
        "Munghana wa mina wa n'wana wa ntsongo u ta hi etela a huma eka vukati hi matlha lamanene hi bese ya sungula.",
        "Hi fanele ku huma eka yindlu hi ku hatlisa namuntlha loko hi lava ku kuma bese ya sungula leyi ya eka doroba.",
        "Mvula yi sungule ku na hi ku hetisekile ku pheka swakudya swa nimugoro hi ri karhi hi lunghelela ku tshama.",
        "Byela tatana wa wena leswaku nhlengeletano ya vaaki yi hundzurile ku suka eka Ravumune ku ya eka Ravunharhu madzahala.",
        "Eka ndlela ya mina yo vuya eka yindlu ku suka emsebenzini, ndzi xavile timawulintshi tinharhu na xinkwa lexintshwa.",
        "Swa teka nkarhi wo tani hi ku famba ku suka exikolweni xo sungula ku ya enambyeni leyi nga eka xiyimo xa doroba?",
    ],
    "tswana": [
        "Dumela, ke solofela gore o robile sentle bosigo jo bo fetileng mme o tsogile sentle gompieno.",
        "Tsweetswee tswala lebati ka morago ga gago o tsene o dule le rona re nwe tee mmogo.",
        "Bana ba tshameka bolo kwa morago ga ntlo fa mme wa bone a sa ntse a baakanya dijo tsa metshehare mo kitchineng.",
        "A o ka nthusa go rwala mokotla ono o boima wa dijo go ya mmerekeng mafelelo a gompieno?",
        "Kgaitsadi ya me e nnye o tla re etela a tswa mo motseng ka bosigo jono mo mosong ka bese ya ntlha.",
        "Re tshwanetse go tswa mo gae ka pela gompieno fa re batla go tshwara bese ya ntlha e e yang mo toropong.",
        "Pula e simologile go na ka matla ka morago ga re qetile go pheka dijo tsa mafelo a bosigo.",
        "Bolelela rraago gore kopano ya sechaba e fetogile go tswa mo Labone go ya mo Labotlhano mafelelo a bosigo.",
        "Tseleng ya me ya go boela gae go tswa mo tirong, ke rekile namune tse tharo le borotho bo bo sa ntshitsweng.",
        "Go tsaya nako e kae go tsamaya go tswa sekolong sa ntlha go ya nokeng e e leng kwa bokhutlong jwa toropo?",
    ],
    "twi": [
        "Mema wo akye, me anidaso ne sɛ woada yie anadwo a atwam na woanhyɛ ase nnɛ anɔpa.",
        "Mepa wo kyɛw, to ɛpono no mu w'akyi na bra fa adidi yɛn ho na yɛnnom tii.",
        "Mmofra no redi agoru wɔ dan no akyi bere a wɔn maame resiesie adidi a wɔbɛdidi awia no wɔ kitchin no mu.",
        "Wobɛtumi aka me bo sɛ mede abura suro yi a ɛwɔ mu no akɔ gua so nnɛ anwummere?",
        "Me nuabea kumaa rebɛba abɛsra yɛn fi kuro mu anɔpa a ɛreba so no wɔ trotro a edi kan no so.",
        "Yɛsɛ hwe yɛn fi ntɛm nnɛ sɛ yɛpɛ sɛ yɛkɔ trotro a edi kan no a ɛkɔ kuro no mu.",
        "Osutɔ fi ase anɔpa bere a yɛawie adidi anadwo no na yɛresiesie sɛ yɛbɛtena ase.",
        "Ka kyerɛ w'agya sɛ nhyiam no afi Yawoada akɔ Fiada anwummere.",
        "Me kwan a mede reba fie fi adwuma no so, metɔɔ ankaa abiɛsa ne paanoo foforo baako.",
        "Ɛbɛkyɛ dɛn ansa na woafiri sukuu a edi kan no nantew akɔ asubɔnten a ɛwɔ kuro no ano no ho?",
    ],
    "umbundu": [
        "Wakolapo, nda tekelela okuti walala ocipalo cokole okuti okuya ocipolo cokele ocipolo cokwava olole.",
        "Feka ocipito okuti ove olume okuti ole okuya okuti olume ole okuti olume ca okuti olume ole.",
        "Omanu va tunga konima yocumbo okuti ame va lusola okuti okuchi okuti okuchila okufika ocipolo.",
        "Okuti ole okuneka okuti nda leka ocisaku cokole okuti okuya komatala ocipolo cokwava ole?",
        "Kuanetu okwame okocokolo okuyenda okutukila okuvela okudidi okuchila ocivili ocipolo cokwava.",
        "Tukwenda okuti tukachoke ocipolo okutya okuti tukwenda okuchila ocivili ocipolo cokole okuchila ocimbila.",
        "Imvula yatanga okuchila okufika ocipolo okuchila okufika ocipolo okuti tukwenda okuti tukachoke ocipolo.",
        "Linga tate okuti ocisonso ocipolo cokwava ocikwenda okuchila okuchila okufika okuchila okufika.",
        "Nda landa olaranja vitatu locimbombo okuchila okufika ocipolo okuti nda vele okuchila okuchila.",
        "Cipwa eteke likuata okuenda kofeleka kuenda komulonga okuchila okuchila okufika ocipolo?",
    ],
    "venda": [
        "Ndaa, ndi khou vhulunga uri vho lala zwavhudi vhusiku ha fhiraho na uri vho fika zwavhudi namusi.",
        "Ndi khou humbela ni vale vothi nga murahu ha nṋe ni dzule na hine kha ngomu ni mina tii.",
        "Vhana vha khou tamba bolo nnḓa ha ṋnḓu musi mme wa vho vha sa athu u lugisa zwiliwa zwa masegare kha kitchini.",
        "Ni nga ndi thusa u tshimbila saḓo iḽi ḽiswa ḽa zwiliwa u ya ḓoroboni namusi madzahala?",
        "Munne waṱuku wanga u ḓo ḓisa u ri vhona u bva kha tshiṱere matshelo na bese ya u thoma.",
        "Ri fanela u bva kha ngomu nga u fhira namusi arali ri khou toda u wana bese ya u thoma i ya ḓoroboni.",
        "Mvula yo thoma u na nga maanda murahu ha u fhedza u pheka zwiliwa zwa mannḓa na ri sa lindela u tshimbila.",
        "Vhudza khotsi anu uri musangano wa vhathu wo shandukwa u bva Lavhuvhili u ya Lavhuṱanu madzahala.",
        "Kha ndila yanga ya u vhuya kha ngomu u bva kha mushumo, ndo renga maorentshi mararu na vhurotho ḽiswa.",
        "Zwi dzhia tshifhinga tshikae u tshimbila u bva tshikoloni tsha u thoma u ya mulamboni wo re kha muhala wa ṱauni?",
    ],
    "wolof": [
        "Jamm nga fanaan, dama yaaka ne nga nelaw ci gëna wanaag te nga fii ci gëna wanaag tey.",
        "Ngalla tëj buntu bi ci ginaaw laay joxe te duggal ci biir ngir jëkk a jëkk ci sunu ndaje.",
        "Xale yi dañuy fo ci ginaaw kër gi ba noppi bi di def lëkk gi ci biir kër gi.",
        "Ndax mën nga ma dimbali yab saaku bu doj bu mbuusu lepp ci yoon wi jëm marché bi ci ngoon wi?",
        "Magam ji jigéen ji dina ñëw ci suba jëme ñu ci dëkk bi ci biir bés bu jëkk bi.",
        "Danaa wara génn ci kër gi ci suba su nu bëgg a jël bés bu jëkk bi jëm dëkk bi.",
        "Tawat dafa tàmbali gannaaw bi nu jeexee lëkk ci ngoon te takhaw ci kër gi.",
        "Waxal sa baay ne réunion bu askan wi délloose na ci Alxamis ca Aljumaa ngoon gi.",
        "Ci yoon bi ma di delloo kër gi ci liggéey bi, dama jënd ñetti orange ak mburu bu bees.",
        "Ñaata waxtu lay jël ngir dox jële ecole bu njëkk bi jëm ba dex bi nekk ci boppu dëkk bi?",
    ],
    "xhosa": [
        "Molo kusasa, ndithemba ukuba ulale kakuhle ngobusuku obudlulileyo kwaye uvuke kakuhle namhlanje.",
        "Nceda uvale ucango ngasemva kwakho uze ungene uhlale nathi singaphuze iti kunye.",
        "Abantwana badlala ibhola ngasemva kwendlu ngelixa umama wabo esakupheka isidlo sasemini ekhishini.",
        "Ungandinceda ndithwale le ngxowa enzima yokutya ukuya emarikethini namhlanje emva kwemini?",
        "Udade wam omncinci uza kusivakashela evela emaphandleni ngomso ekuseni ngebhasi yokuqala.",
        "Kufuneka siphume ekhaya ngokukhawuleza namhlanje ukuba sifuna ukubamba ibhasi yokuqala eya edolobheni.",
        "Imvula yaqala ukuna ngamandla emva kokuba sigqibe ukupheka isidlo sakusihlwa sibe silungele ukuhlala phantsi.",
        "Xelela uyihlo ukuba intlanganiso yoluntu isuswe ukusuka ngoLwesine ukuya ngoLwesihlanu emva kwemini.",
        "Endleleni yam yokubuya ekhaya emsebenzini, ndithenge amaorenji amathathu nesonka esitsha.",
        "Kuthatha ixesha elingakanani ukuhamba usuka esikolweni sokuqala uye emlanjeni okusekupheleni kwedolobha?",
    ],
    "yoruba": [
        "E kaaro, mo reti pe o sun dada lale ana ati pe o ji dada loni owurọ.",
        "Jowo ti ilekun lehin re wa si wa joko ki a mu tii papo.",
        "Awon omo n sere pelu bọọlu lehin ile nigba ti iya won n pese ounje owurọ ninu ile idana.",
        "Se o le ran mi lowo lati gbe apo wuwo yi ti o kun fun ounjẹ lo si oja loni owurọ?",
        "Arabinrin kekere mi yoo wa beere wa lati ilu ni owurọ ola lori bosi akoko.",
        "A nilo lati ma kuro ni ile ni kiakia loni bi a ba fe mu bosi akoko lo si ilu.",
        "Ojo bẹrẹ lati ro pupọ lẹhin ti a ti pari sisẹ ounje ale ati pe a n setan lati joko.",
        "So fun baba re pe ipade agbegbe ti yipada lati Ojo Alhamisi si Ojo Jimọ lọsan.",
        "Lori ona mi si ile lati ise, mo ra osan meta ati akara tuntun kan.",
        "Igbawo ni o n gba lati rin lati ile-iwe akoko lo si odo ti o wa ni eti ilu?",
    ],
    "zulu": [
        "Sawubona ekuseni, ngiyethemba ukuthi ulale kahle ebusuku obudlule futhi uvuke kahle namuhla ekuseni.",
        "Ngicela uvale umnyango ngemuva kwakho bese ungena uhlale nathi singaphuze itiye ndawonye.",
        "Izingane zidlala ibhola ngemuva kwendlu ngenkathi umama wazo esakupheka isidlo sasemini ekhishini.",
        "Ungangisiza ngithwale lesi sakhi esisindayo sokudla siye emakethe namuhla emini?",
        "Udade wami omncane uzoza kusivakashela evela emaphandleni kusasa ekuseni ngebhasi yokuqala.",
        "Kufanele siphume ekhaya ngokushesha namuhla uma sifuna ukubamba ibhasi yokuqala eya edolobheni.",
        "Imvula yaqala ukuna kakhulu ngemva kokuba sesiqedile ukupheka isidlo sakusihlwa sibe silungele ukuhlala phansi.",
        "Tshela uyihlo ukuthi umhlangano womphakathi ususwe kusukela ngoLwesine uye ngoLwesihlanu emini.",
        "Endleleni yami yokubuyela ekhaya emsebenzini, ngiyethe ngathenga amawolintshi amathathu nesinkwa esisha.",
        "Kuthatha isikhathi esingakanani ukuhamba uvela esikoleni sokuqala uye emfuleni okusekupheleni kwedolobha?",
    ],
}


def _clean(lines: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for line in lines:
        text = " ".join((line or "").split())
        if not text or "\ufffd" in text or text.upper().startswith("[PLACEHOLDER]"):
            continue
        if text in seen:
            continue
        seen.add(text)
        out.append(text)
    return out


def main() -> int:
    problems: list[str] = []
    if set(SENTENCES) != set(CODES):
        problems.append(f"key mismatch {set(SENTENCES) ^ set(CODES)}")
    for language, lines in list(SENTENCES.items()):
        SENTENCES[language] = _clean(lines)
        cleaned = SENTENCES[language]
        if len(cleaned) != 10:
            problems.append(f"{language} has {len(cleaned)} clean lines")
    if problems:
        print("\n".join(problems))
        return 1

    rows = []
    for language, lines in SENTENCES.items():
        code = CODES[language]
        for index, text in enumerate(lines, start=1):
            rows.append(
                {
                    "sentence_id": f"{code}-{index:03d}",
                    "language": language,
                    "accent": "",
                    "text": text,
                }
            )

    buffer = io.StringIO(newline="")
    writer = csv.DictWriter(
        buffer,
        fieldnames=["sentence_id", "language", "accent", "text"],
        lineterminator="\n",
    )
    writer.writeheader()
    writer.writerows(rows)
    OUT.write_text(buffer.getvalue(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(PROJECT_ROOT)} ({len(rows)} sentences)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
